event entity @s[tag=aug_silencer] mk556:silencer
event entity @s[tag=aug_brake] mk556:brake
event entity @s[tag=augcompensator] mk556:compensator
event entity @s[tag=augdrum] mk556:drum
event entity @s[tag=augeo] mk556:eo
event entity @s[tag=augholo] mk556:holo
event entity @s[tag=augreddot] mk556:reddot
event entity @s[tag=augacog] mk556:acog
event entity @s[tag=augred] mk556:laser
event entity @s[tag=auggreen] mk556:laser2
event entity @s[tag=auggold] mk556:laser3
event entity @s[tag=augshort] mk556:short
event entity @s[tag=auglong] mk556:long
event entity @s[tag=auglight] mk556:light
event entity @s[tag=aughamr] mk556:hamr
event entity @s[tag=augnomag] hengker:nomag
event entity @s[tag=!augnomag] hengker:mag
event entity @s[tag=!augholo,tag=!augreddot,tag=!augeo,tag=!augacog,tag=!aughamr] mk556:sight
event entity @s[tag=!augred,tag=!auggreen,tag=!auggold] mk556:laser_off
event entity @s[tag=!aug_brake,tag=!aug_silencer,tag=!augcompensator] mk556:muzzle
event entity @s[tag=!augdrum] mk556:mag
event entity @s[tag=!auglong,tag=!augshort,tag=!auglight] mk556:grip