event entity @s[tag=hkc_silencer] mk556:silencer
event entity @s[tag=hkc_brake] mk556:brake
event entity @s[tag=hkccompensator] mk556:compensator
event entity @s[tag=hkcdrum] mk556:drum
event entity @s[tag=hkcmagnifier] mk556:magnifier
event entity @s[tag=hkcholo] mk556:holo
event entity @s[tag=hkcreddot] mk556:reddot
event entity @s[tag=hkcacog] mk556:acog
event entity @s[tag=hkcred] mk556:laser
event entity @s[tag=hkcgreen] mk556:laser2
event entity @s[tag=hkcgold] mk556:laser3
event entity @s[tag=hkcshort] mk556:short
event entity @s[tag=hkclong] mk556:long
event entity @s[tag=hkclight] mk556:light
event entity @s[tag=hkctele] mk556:tele
event entity @s[tag=hkcnomag] hengker:nomag
event entity @s[tag=!hkcnomag] hengker:mag
event entity @s[tag=hkcdrum] mk556:drum
event entity @s[tag=hkcsimple] mk556:simple
event entity @s[tag=hkcnormal] mk556:normal
event entity @s[tag=hkccqb] mk556:cqb
event entity @s[tag=hkcextended] mk556:extended
event entity @s[tag=!hkcholo,tag=!hkcreddot,tag=!hkcmagnifier,tag=!hkcacog,tag=!hkctele] mk556:sight
event entity @s[tag=!hkcred,tag=!hkcgreen,tag=!hkcgold] mk556:laser_off
event entity @s[tag=!hkc_brake,tag=!hkc_silencer,tag=!hkccompensator] mk556:muzzle
event entity @s[tag=!hkcdrum,tag=!hkcextended] mk556:mag
event entity @s[tag=!hkclong,tag=!hkcshort,tag=!hkclight] mk556:grip
event entity @s[tag=!hkcnormal,tag=!hkcsimple,tag=!hkccqb] mk556:stock