event entity @s[tag=tactileholo] mk556:holo
event entity @s[tag=tactilereddot] mk556:reddot
event entity @s[tag=tactileacog] mk556:acog
event entity @s[tag=tactilered] mk556:laser
event entity @s[tag=tactilegreen] mk556:laser2
event entity @s[tag=tactilegold] mk556:laser3
event entity @s[tag=tactilescout] mk556:scout
event entity @s[tag=tactilenomag] hengker:nomag
event entity @s[tag=!tactilenomag] hengker:mag
event entity @s[tag=!tactileholo,tag=!tactilereddot,tag=!tactileacog,tag=!tactilescout] mk556:sight
event entity @s[tag=!tactilered,tag=!tactilegreen,tag=!tactilegold] mk556:laser_off