export const CONFIG = Object.freeze({
  version: "0.6.0",
  dimensionId: "apoc_extract:city",
  heartbeatKey: "interop:apoc_extraction_heartbeat",
  menuRequestKey: "interop:apoc_extraction_menu_request:v1",
  menuAckKey: "interop:apoc_extraction_ack",
  cityReadyKey: "apoc_extract:city_ready:v4",
  previousCityReadyKey: "apoc_extract:city_ready:v3",
  cityReadyBackupKey: "apoc_extract:city_ready_backup:v1",
  citySentinel: { x: 0, y: 62, z: 0 },
  activeTag: "apoc_extraction_active",
  activeStateKey: "apoc_extract:active:v1",
  returnKey: "apoc_extract:return:v1",
  deathReturnKey: "apoc_extract:death_return:v1",
  pointsKey: "apoc_extract:points:v1",
  lootNodesKey: "apoc:loot_nodes:v1",
  apocalypseHeartbeatKey: "apoc:heartbeat",
  fogId: "apoc_extract:dusk_fog",
  fogStackId: "apoc_extract_city_environment",
  keepInventoryRequired: true,
  protectedHotbarSlots: 9,
  extractionRadius: 9,
  extractionSeconds: 10,
  cityBaseY: 63,
  cityHalfSize: 384,
  cityTileSize: 128,
  districtSpacing: 128,
  districtCenters: [
    { x: -256, z: -256 }, { x: -128, z: -256 }, { x: 0, z: -256 }, { x: 128, z: -256 }, { x: 256, z: -256 },
    { x: -256, z: -128 }, { x: -128, z: -128 }, { x: 0, z: -128 }, { x: 128, z: -128 }, { x: 256, z: -128 },
    { x: -256, z: 0 }, { x: -128, z: 0 }, { x: 0, z: 0 }, { x: 128, z: 0 }, { x: 256, z: 0 },
    { x: -256, z: 128 }, { x: -128, z: 128 }, { x: 0, z: 128 }, { x: 128, z: 128 }, { x: 256, z: 128 },
    { x: -256, z: 256 }, { x: -128, z: 256 }, { x: 0, z: 256 }, { x: 128, z: 256 }, { x: 256, z: 256 }
  ],
  hostileCapPerPlayer: 12,
  hostileSpawnIntervalTicks: 80,
  bossCheckIntervalTicks: 1200,
  bossChancePerCheck: 0.08,
  hordeCheckIntervalTicks: 1200,
  hordeChancePerCheck: 0.12,
  hordeCooldownTicks: 12000,
  hordeWaveTimeoutTicks: 1200,
  entryPoints: [
    { name: "西北旧城", x: -256, z: -256 }, { name: "北部商业区", x: 0, z: -256 },
    { name: "东北住宅区", x: 256, z: -256 }, { name: "西部工业区", x: -256, z: 0 },
    { name: "中央城区", x: 0, z: 0 }, { name: "东部办公区", x: 256, z: 0 },
    { name: "西南仓储区", x: -256, z: 256 }, { name: "南部医院区", x: 0, z: 256 },
    { name: "东南交通区", x: 256, z: 256 }
  ],
  extractionPoints: [
    { id: "metro_north_west", name: "西北地铁口", x: -256, z: -352 },
    { id: "metro_north", name: "北部地铁口", x: 0, z: -352 },
    { id: "checkpoint_north_east", name: "东北检查站", x: 256, z: -352 },
    { id: "rail_west_north", name: "西北铁路", x: -352, z: -256 },
    { id: "rail_west", name: "西部铁路", x: -352, z: 0 },
    { id: "sewer_west_south", name: "西南下水道", x: -352, z: 256 },
    { id: "bridge_east_north", name: "东北断桥", x: 352, z: -256 },
    { id: "bridge_east", name: "东部断桥", x: 352, z: 0 },
    { id: "service_east_south", name: "东南维修通道", x: 352, z: 256 },
    { id: "factory_south_west", name: "废厂后门", x: -256, z: 352 },
    { id: "tunnel_south", name: "南部隧道", x: 0, z: 352 },
    { id: "hospital_south_east", name: "医院停机坪", x: 256, z: 352 }
  ],
  mobPool: [
    { key: "mutant", weight: 18 }, { key: "heavy", weight: 15 },
    { key: "spitter", weight: 13 }, { key: "runner", weight: 8 },
    { key: "shrieker", weight: 10 }, { key: "charger", weight: 11 },
    { key: "hunter", weight: 12 }, { key: "tyrant", weight: 3 },
    { key: "raider", weight: 10 }
  ],
  bossPool: [
    { id: "apoc_boss:fog_man", weight: 26, urbanLegend: true },
    { id: "apoc_boss:goatman", weight: 22, urbanLegend: true },
    { id: "apoc_boss:siren_head", weight: 18, urbanLegend: true },
    { id: "apoc_boss:mutant_zombie", weight: 10 },
    { id: "apoc_boss:mutant_skeleton", weight: 8 },
    { id: "apoc_boss:mutant_lobber", weight: 6 },
    { id: "apoc_boss:mutant_drowned", weight: 4 },
    { id: "apoc_boss:mutant_enderman", weight: 3 },
    { id: "apoc_boss:mutant_iron_golem", weight: 3 }
    ,{ id: "apoc:infected_broodmother", weight: 1, urbanLegend: false }
  ]
});
