scoreboard players add @s[hasitem={item=leather_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 1
scoreboard players add @s[hasitem={item=leather_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=leather_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=leather_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 1
scoreboard players add @s[hasitem={item=golden_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=golden_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=golden_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=golden_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 1
scoreboard players add @s[hasitem={item=chainmail_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=chainmail_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=chainmail_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 4
scoreboard players add @s[hasitem={item=chainmail_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 1
scoreboard players add @s[hasitem={item=iron_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=iron_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 6
scoreboard players add @s[hasitem={item=iron_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=iron_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=diamond_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=diamond_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 8
scoreboard players add @s[hasitem={item=diamond_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 6
scoreboard players add @s[hasitem={item=diamond_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=netherite_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=netherite_chestplate, location=slot.armor.chest, slot=0}] L4gg-armorPoints 8
scoreboard players add @s[hasitem={item=netherite_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 6
scoreboard players add @s[hasitem={item=netherite_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=turtle_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=hengker:ghost_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=hengker:advanced_vest, location=slot.armor.chest, slot=0}] L4gg-armorPoints 9
scoreboard players add @s[hasitem={item=hengker:advanced_leggings, location=slot.armor.legs, slot=0}] L4gg-armorPoints 7
scoreboard players add @s[hasitem={item=hengker:advanced_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=hengker:hazmat_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=armor:hazmat_suit, location=slot.armor.chest, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=armor:hazmat_pants, location=slot.armor.legs, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=armor:hazmat_boots, location=slot.armor.feet, slot=0}] L4gg-armorPoints 1
scoreboard players add @s[hasitem={item=bridge:t1_helmet_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 2
scoreboard players add @s[hasitem={item=bridge:t2_helmet_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 3
scoreboard players add @s[hasitem={item=bridge:t3_helmet_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 4
scoreboard players add @s[hasitem={item=bridge:t4_helmet_helmet, location=slot.armor.head, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=hengker:t4_vest, location=slot.armor.chest, slot=0}] L4gg-armorPoints 7
scoreboard players add @s[hasitem={item=hengker:t3_vest, location=slot.armor.chest, slot=0}] L4gg-armorPoints 5
scoreboard players add @s[hasitem={item=hengker:t2_vest, location=slot.armor.chest, slot=0}] L4gg-armorPoints 4
scoreboard players add @s[hasitem={item=hengker:t1_vest, location=slot.armor.chest, slot=0}] L4gg-armorPoints 3