event entity @s[tag=hbdrum] mk556:drum
event entity @s[tag=hbmagnifier] mk556:magnifier
event entity @s[tag=hbholo] mk556:holo
event entity @s[tag=hbreddot] mk556:reddot
event entity @s[tag=hbacog] mk556:acog
event entity @s[tag=hbred] mk556:laser
event entity @s[tag=hbgreen] mk556:laser2
event entity @s[tag=hbgold] mk556:laser3
event entity @s[tag=hbsimple] mk556:simple
event entity @s[tag=hbnormal] mk556:normal
event entity @s[tag=hbcqb] mk556:cqb
event entity @s[tag=hbtele] mk556:tele
event entity @s[tag=hbnomag] hengker:nomag
event entity @s[tag=!hbnomag] hengker:mag
event entity @s[tag=hbdrum] mk556:drum
event entity @s[tag=hbextended] mk556:extended
event entity @s[tag=!hbholo,tag=!hbreddot,tag=!hbmagnifier,tag=!hbacog,tag=!hbtele] mk556:sight
event entity @s[tag=!hbred,tag=!hbgreen,tag=!hbgold] mk556:laser_off
event entity @s[tag=!hbdrum,tag=!hbextended] mk556:mag
event entity @s[tag=!hbnormal,tag=!hbsimple,tag=!hbcqb] mk556:stock