event entity @s[tag=scar_silencer] mk556:silencer
event entity @s[tag=scar_brake] mk556:brake
event entity @s[tag=scarcompensator] mk556:compensator
event entity @s[tag=scardrum] mk556:drum
event entity @s[tag=scarmagnifier] mk556:magnifier
event entity @s[tag=scarholo] mk556:holo
event entity @s[tag=scarreddot] mk556:reddot
event entity @s[tag=scaracog] mk556:acog
event entity @s[tag=scarred] mk556:laser
event entity @s[tag=scargreen] mk556:laser2
event entity @s[tag=scargold] mk556:laser3
event entity @s[tag=scarshort] mk556:short
event entity @s[tag=scarlong] mk556:long
event entity @s[tag=scarlight] mk556:light
event entity @s[tag=scartele] mk556:tele
event entity @s[tag=scarnomag] hengker:nomag
event entity @s[tag=!scarnomag] hengker:mag
event entity @s[tag=scardrum] mk556:drum
event entity @s[tag=scarextended] mk556:extended
event entity @s[tag=!scarholo,tag=!scarreddot,tag=!scarmagnifier,tag=!scaracog,tag=!scartele] mk556:sight
event entity @s[tag=!scarred,tag=!scargreen,tag=!scargold] mk556:laser_off
event entity @s[tag=!scar_brake,tag=!scar_silencer,tag=!scarcompensator] mk556:muzzle
event entity @s[tag=!scardrum,tag=!scarextended] mk556:mag
event entity @s[tag=!scarlong,tag=!scarshort,tag=!scarlight] mk556:grip